#!/bin/bash

log () {
  echo -e "  \E[32m$1\E[0m  $2"
}
export -f log
export PATH=$HOME/bin:$PATH

curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/prepare | sh
curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_packages | sh

curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_zsh | sh
curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_vim | sh
curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_tmux | sh

curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_rbenv | sh
curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_ruby | sh
curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_gems | sh

curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_dotfiles | sh
curl -s https://raw.githubusercontent.com/williamcodes/dotfiles/master/lib/install_vim_plugins | sh

log "done"
