#!/bin/bash

log () {
  echo -e "  \E[32m$1\E[0m  $2"
}
export -f log
export PATH=$HOME/bin:$PATH

curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/prepare | bash sh
curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_packages | bash sh

curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_zsh | bash sh
curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_vim | bash sh
curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_tmux | bash sh

curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_rbenv | bash sh
curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_ruby | bash sh
curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_gems | bash sh

curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_dotfiles | bash sh
curl -s https://raw.githubusercontent.com/thedeeno/dotfiles/master/lib/install_vim_plugins | bash sh

log "done"
