
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
zstyle ':prezto:module:terminal' auto-title 'no'

autoload -U colors && colors

# Source customizations
for file in $HOME/.zsh/*.zsh; do
  if [ -f "$file" ] ; then
    source "$file"
  fi
done

# RBENV
eval "$(rbenv init -)"

# Node Version Manager
source $(brew --prefix nvm)/nvm.sh

# use dvorak as the basis for spell checking
# setopt DVORAK
unsetopt correct_all

# start tmux by default
# if [[ ! $TERM =~ screen ]]; then
#   $(tmux)
# fi

export PATH="$HOME/.ndenv/bin:$PATH"
eval "$(ndenv init -)"
