#!/bin/bash

# install ruby
export PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH
export RBENV_VERSION="2.1.1"
ruby_version="2.1.1"
log "build" "ruby $ruby_version"
rbenv install $ruby_version
rbenv rehash


