#!/bin/bash

log "install" "packages"

apt-get install -y \
  curl               \
  build-essential    \
  git-core           \
  git-gui            \
  gitg               \
  libssl-dev         \
  libxml2-dev        \
  libxslt-dev        \
  openssl            \
  grep               \
  zsh

